name: DevOps CI Pipeline

on:
  push:
    branches: [main, dev]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --run

      - name: Build
        run: npm run build

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker Build
        run: docker build -t oussamazid/frontend:latest .


      - name: Trivy Scan Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: oussamazid/frontend:latest
          severity: CRITICAL,HIGH
          exit-code: 1

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker Build
        run: docker build -t oussamazid/backend:latest .

      - name: docker push
        run: docker push oussamazid/backend:latest

  sonar:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
        args: >
          -Dsonar.projectKey=zidoussama_projectdevops
          -Dsonar.organization=zidoussama
          -Dsonar.sources=frontend,backend